name: Release

on:
  push:
    tags:
      - 'v*' # trigger only on tag push

jobs:
  build:
    name: Build native bindings
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:

      - uses: actions/checkout@v5

      # Install Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true

      # Install Rust
      - uses: dtolnay/rust-toolchain@stable

      # Cache Cargo for faster builds
      - uses: Swatinem/rust-cache@v2

      # Install dependencies
      - run: npm ci

      - name: Install napi CLI
        run: npm install --global @napi-rs/cli
      # Build native bindings for this OS only
      - name: Build bindings
        run: napi build --release --platform

      # Upload OS-specific artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.os }}
          path: npm/*
      - run: ls -R npm


  publish:
    name: Publish to npm
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # Download artifacts from all OSes
      - uses: actions/download-artifact@v4
        with:
          name: bindings-ubuntu-latest
          path: ./npm
      - uses: actions/download-artifact@v4
        with:
          name: bindings-macos-latest
          path: ./npm
      - uses: actions/download-artifact@v4
        with:
          name: bindings-windows-latest
          path: ./npm

      # Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      # Authenticate npm
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      # Publish package
      - run: npm publish --access public
        working-directory: ./npm/math-utils-rs
